version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: expo
    versions:
    - 40.0.1
    - 41.0.0
  - dependency-name: cypress
    versions:
    - 6.3.0
    - 6.4.0
    - 6.5.0
    - 6.6.0
    - 6.7.1
    - 6.8.0
    - 7.0.0
    - 7.0.1
    - 7.1.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.1
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: react-native-screens
    versions:
    - 2.17.1
    - 2.18.0
    - 2.18.1
    - 3.0.0
    - 3.1.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: react-native-reanimated
    versions:
    - 1.13.2
    - 2.0.0
    - 2.0.1
  - dependency-name: react-native-gesture-handler
    versions:
    - 1.10.0
    - 1.10.1
    - 1.10.2
    - 1.9.0
  - dependency-name: "@react-navigation/native"
    versions:
    - 5.9.2
    - 5.9.3
  - dependency-name: "@react-navigation/stack"
    versions:
    - 5.14.2
    - 5.14.3
  - dependency-name: react-native-web
    versions:
    - 0.14.10
    - 0.14.11
    - 0.14.12
  - dependency-name: start-server-and-test
    versions:
    - 1.11.7
    - 1.12.0
  - dependency-name: expo-status-bar
    versions:
    - 1.0.3
  - dependency-name: react-native-safe-area-context
    versions:
    - 3.1.9
